#!/bin/sh

set -e

# Start supervisor and apply lldpad configuration
service supervisor start

##
# For volume mounts...
##
chown -R frr:frr /etc/frr
/etc/init.d/frr start
/usr/sbin/sshd -D
exec sleep 10000d
