##
## Copyright (c) 2020-2021 NVIDIA CORPORATION & AFFILIATES.
## Apache-2.0
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
# name           lanes                alias            index
Ethernet0         0,1                 etp1a              1
Ethernet2         2,3                 etp1b              1
Ethernet4         8,9                 etp2a              2
Ethernet6         10,11               etp2b              2
Ethernet8         16,17               etp3a              3
Ethernet10        18,19               etp3b              3
Ethernet12        24,25               etp4a              4
Ethernet14        26,27               etp4b              4
Ethernet16        32,33               etp5a              5
Ethernet18        34,35               etp5b              5
Ethernet20        40,41               etp6a              6
Ethernet22        42,43               etp6b              6
Ethernet24        48,49               etp7a              7
Ethernet26        50,51               etp7b              7
Ethernet28        56,57               etp8a              8
Ethernet30        58,59               etp8b              8
Ethernet32        64,65               etp9a              9
Ethernet34        66,67               etp9b              9
Ethernet36        72,73               etp10a              10
Ethernet38        74,75               etp10b              10
Ethernet40        80,81               etp11a              11
Ethernet42        82,83               etp11b              11
Ethernet44        88,89               etp12a              12
Ethernet46        90,91               etp12b              12
Ethernet48        96,97               etp13a              13
Ethernet50        98,99               etp13b              13
Ethernet52        104,105               etp14a              14
Ethernet54        106,107               etp14b              14
Ethernet56        112,113               etp15a              15
Ethernet58        114,115               etp15b              15
Ethernet60        120,121               etp16a              16
Ethernet62        122,123               etp16b              16
Ethernet64        128,129               etp17a              17
Ethernet66        130,131               etp17b              17
Ethernet68        136,137               etp18a              18
Ethernet70        138,139               etp18b              18
Ethernet72        144,145               etp19a              19
Ethernet74        146,147               etp19b              19
Ethernet76        152,153               etp20a              20
Ethernet78        154,155               etp20b              20
Ethernet80        160,161               etp21a              21
Ethernet82        162,163               etp21b              21
Ethernet84        168,169               etp22a              22
Ethernet86        170,171               etp22b              22
Ethernet88        176,177               etp23a              23
Ethernet90        178,179               etp23b              23
Ethernet92        184,185               etp24a              24
Ethernet94        186,187               etp24b              24
Ethernet96        192,193               etp25a              25
Ethernet98        194,195               etp25b              25
Ethernet100        200,201               etp26a              26
Ethernet102        202,203               etp26b              26
Ethernet104        208,209               etp27a              27
Ethernet106        210,211               etp27b              27
Ethernet108        216,217               etp28a              28
Ethernet110        218,219               etp28b              28
Ethernet112        224,225               etp29a              29
Ethernet114        226,227               etp29b              29
Ethernet116        232,233               etp30a              30
Ethernet118        234,235               etp30b              30
Ethernet120        240,241               etp31a              31
Ethernet122        242,243               etp31b              31
Ethernet124        248,249               etp32a              32
Ethernet126        250,251               etp32b              32
Ethernet128        256,257               etp33a              33
Ethernet130        258,259               etp33b              33
Ethernet132        264,265               etp34a              34
Ethernet134        266,267               etp34b              34
Ethernet136        272,273               etp35a              35
Ethernet138        274,275               etp35b              35
Ethernet140        280,281               etp36a              36
Ethernet142        282,283               etp36b              36
Ethernet144        288,289               etp37a              37
Ethernet146        290,291               etp37b              37
Ethernet148        296,297               etp38a              38
Ethernet150        298,299               etp38b              38
Ethernet152        304,305               etp39a              39
Ethernet154        306,307               etp39b              39
Ethernet156        312,313               etp40a              40
Ethernet158        314,315               etp40b              40
Ethernet160        320,321               etp41a              41
Ethernet162        322,323               etp41b              41
Ethernet164        328,329               etp42a              42
Ethernet166        330,331               etp42b              42
Ethernet168        336,337               etp43a              43
Ethernet170        338,339               etp43b              43
Ethernet172        344,345               etp44a              44
Ethernet174        346,347               etp44b              44
Ethernet176        352,353               etp45a              45
Ethernet178        354,355               etp45b              45
Ethernet180        360,361               etp46a              46
Ethernet182        362,363               etp46b              46
Ethernet184        368,369               etp47a              47
Ethernet186        370,371               etp47b              47
Ethernet188        376,377               etp48a              48
Ethernet190        378,379               etp48b              48
Ethernet192        384,385               etp49a              49
Ethernet194        386,387               etp49b              49
Ethernet196        392,393               etp50a              50
Ethernet198        394,395               etp50b              50
Ethernet200        400,401               etp51a              51
Ethernet202        402,403               etp51b              51
Ethernet204        408,409               etp52a              52
Ethernet206        410,411               etp52b              52
Ethernet208        416,417               etp53a              53
Ethernet210        418,419               etp53b              53
Ethernet212        424,425               etp54a              54
Ethernet214        426,427               etp54b              54
Ethernet216        432,433               etp55a              55
Ethernet218        434,435               etp55b              55
Ethernet220        440,441               etp56a              56
Ethernet222        442,443               etp56b              56
Ethernet224        448,449               etp57a              57
Ethernet226        450,451               etp57b              57
Ethernet228        456,457               etp58a              58
Ethernet230        458,459               etp58b              58
Ethernet232        464,465               etp59a              59
Ethernet234        466,467               etp59b              59
Ethernet236        472,473               etp60a              60
Ethernet238        474,475               etp60b              60
Ethernet240        480,481               etp61a              61
Ethernet242        482,483               etp61b              61
Ethernet244        488,489               etp62a              62
Ethernet246        490,491               etp62b              62
Ethernet248        496,497               etp63a              63
Ethernet250        498,499               etp63b              63
Ethernet252        504,505,506,507       etp64               64
