# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ngts.tests_nvos.general.security.nmx_cert.grpc.proto import \
    nmx_m_nmx_c_pb2 as ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2


class NMX_ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
            '/nmx_c.NMX_Controller/Hello',
            request_serializer=ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ClientHello.SerializeToString,
            response_deserializer=ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ServerHello.FromString,
        )


class NMX_ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Initial RPC call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NMX_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Hello': grpc.unary_unary_rpc_method_handler(
            servicer.Hello,
            request_deserializer=ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ClientHello.FromString,
            response_serializer=ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ServerHello.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'nmx_c.NMX_Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class NMX_Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nmx_c.NMX_Controller/Hello',
                                             ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ClientHello.SerializeToString,
                                             ngts_dot_tests__nvos_dot_general_dot_security_dot_nmx__cert_dot_grpc_dot_proto_dot_nmx__m__nmx__c__pb2.ServerHello.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
