# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ngts/tests_nvos/general/security/nmx_cert/grpc/proto/nmx-m-nmx-c.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFngts/tests_nvos/general/security/nmx_cert/grpc/proto/nmx-m-nmx-c.proto\x12\x05nmx_c\"(\n\nKeyValPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"p\n\x0cServerHeader\x12\x13\n\x0b\x64omain_uuid\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_uuid\x18\x02 \x01(\t\x12\x0f\n\x07\x61pp_ver\x18\x03 \x01(\t\x12(\n\nreturnCode\x18\x04 \x01(\x0e\x32\x14.nmx_c.ST_ReturnCode\"\x88\x01\n\x0b\x43lientHello\x12\x11\n\tgatewayId\x18\x01 \x01(\t\x12\x32\n\rmajor_version\x18\x02 \x01(\x0e\x32\x1b.nmx_c.ProtoMsgMajorVersion\x12\x32\n\rminor_version\x18\x03 \x01(\x0e\x32\x1b.nmx_c.ProtoMsgMinorVersion\"\xfa\x01\n\x0bServerHello\x12)\n\x0cserverHeader\x18\x01 \x01(\x0b\x32\x13.nmx_c.ServerHeader\x12)\n\x0e\x63omponents_ver\x18\x02 \x03(\x0b\x32\x11.nmx_c.KeyValPair\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t\x12\x17\n\x0fhost_os_details\x18\x04 \x01(\t\x12\x32\n\rmajor_version\x18\x05 \x01(\x0e\x32\x1b.nmx_c.ProtoMsgMajorVersion\x12\x32\n\rminor_version\x18\x06 \x01(\x0e\x32\x1b.nmx_c.ProtoMsgMinorVersion*Z\n\x14ProtoMsgMajorVersion\x12%\n!PROTO_MSG_MAJOR_VERSION_UNDEFINED\x10\x00\x12\x1b\n\x17PROTO_MSG_MAJOR_VERSION\x10\x01*Z\n\x14ProtoMsgMinorVersion\x12%\n!PROTO_MSG_MINOR_VERSION_UNDEFINED\x10\x00\x12\x1b\n\x17PROTO_MSG_MINOR_VERSION\x10\x01*\xfe\x01\n\rST_ReturnCode\x12\x10\n\x0cST_UNDEFINED\x10\x00\x12\x0e\n\nST_SUCCESS\x10\x01\x12\x0f\n\x0bST_BADPARAM\x10\x02\x12\x14\n\x10ST_GENERIC_ERROR\x10\x03\x12\x14\n\x10ST_NOT_SUPPORTED\x10\x04\x12\x14\n\x10ST_UNINITIALIZED\x10\x05\x12\x0e\n\nST_TIMEOUT\x10\x06\x12\x17\n\x13ST_VERSION_MISMATCH\x10\x07\x12\r\n\tST_IN_USE\x10\x08\x12\x15\n\x11ST_NOT_CONFIGURED\x10\t\x12\x1b\n\x17ST_CONNECTION_NOT_VALID\x10\n\x12\x0c\n\x08ST_ERROR\x10\x0b\x32\x43\n\x0eNMX_Controller\x12\x31\n\x05Hello\x12\x12.nmx_c.ClientHello\x1a\x12.nmx_c.ServerHello\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ngts.tests_nvos.general.security.nmx_cert.grpc.proto.nmx_m_nmx_c_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _PROTOMSGMAJORVERSION._serialized_start = 629
    _PROTOMSGMAJORVERSION._serialized_end = 719
    _PROTOMSGMINORVERSION._serialized_start = 721
    _PROTOMSGMINORVERSION._serialized_end = 811
    _ST_RETURNCODE._serialized_start = 814
    _ST_RETURNCODE._serialized_end = 1068
    _KEYVALPAIR._serialized_start = 81
    _KEYVALPAIR._serialized_end = 121
    _SERVERHEADER._serialized_start = 123
    _SERVERHEADER._serialized_end = 235
    _CLIENTHELLO._serialized_start = 238
    _CLIENTHELLO._serialized_end = 374
    _SERVERHELLO._serialized_start = 377
    _SERVERHELLO._serialized_end = 627
    _NMX_CONTROLLER._serialized_start = 1070
    _NMX_CONTROLLER._serialized_end = 1137
# @@protoc_insertion_point(module_scope)
