import os
SETUPS_FOLDER_PATH = "/auto/sw_regression/system/SONIC/MARS/conf/setups"
TOPO_FOLDER_PATH = "/auto/sw_regression/system/SONIC/MARS/conf/topo"
SETUP_TEMPLATE_FILE = "setup_template.setup"
TEMPLATE_FOLDER_PATH = os.path.dirname(os.path.abspath(__file__)) + "/templates"
TOPO_TEMPLATE_FILE = "topology_template.xml"
NOGA_MANAGE_SCRIPT = "/.autodirect/sw_tools/Internal/Noga/RELEASE/latest/cli/noga_manage.py"
NOGA_UPDATE_ATTR_SCRIPT = "/.autodirect/sw_tools/Internal/Noga/RELEASE/latest/import/noga_update_attr.py"
NOGA_LABELS_SCRIPT = "/.autodirect/sw_tools/Internal/Noga/RELEASE/latest/import/manage_labels.py"
RESULTS_FOLDER_PATH = "/auto/sw_regression/system/SONIC/MARS/results"
SPIN_AIR_RESULTS_FOLDER_PATH = "/auto/mtrsysgwork/svc-nbu-sws-sonic/results_spin_air/"
GLOBAL_CONF_FILE = "/auto/sw_regression/system/SONIC/MARS/conf/global/MARS_SONiC_setups_mgr_docker.conf"
LOCAL_CONF_FILE = "/auto/sw_regression/system/SONIC/MARS/conf/global/setups_mgr_local_mtr-stm-095.conf"
MINI_MARS_RUNNER_FILE = "/auto/sw_tools/Internal/MARS/mars_apps/RELEASE/last_release/bin/mini_mars_runner.py"
START_SONIC_MGMT_DOCKER = "/.autodirect/sw_tools/Internal/MARS/mars_apps/RELEASE/last_release/bin/start_sonic_mgmt_docker.py"

STM = "mtr-stm-095"
STM_USER = "root"
STM_PASSWORD = "3tango"
