from copy import deepcopy
from tests.dash.configs.privatelink_config import *

APPLIANCE_VIP = "10.3.0.5"
PE_PA = "101.1.3.3"
ENI_MAC = "F4:93:9F:EF:C4:7D"

APPLIANCE_CONFIG = deepcopy(APPLIANCE_CONFIG)
APPLIANCE_CONFIG[f"DASH_APPLIANCE_TABLE:{APPLIANCE_ID}"]["sip"] = APPLIANCE_VIP
ENI_CONFIG = deepcopy(ENI_CONFIG)
ENI_CONFIG[f"DASH_ENI_TABLE:{ENI_ID}"]["mac_address"] = ENI_MAC
PE_VNET_MAPPING_CONFIG = deepcopy(PE1_VNET_MAPPING_CONFIG)
PE_VNET_MAPPING_CONFIG[f"DASH_VNET_MAPPING_TABLE:{VNET1}:{PE1_CA}"]["underlay_ip"] = PE_PA
ENI_CONFIG[f"DASH_ENI_TABLE:{ENI_ID}"]["pl_underlay_sip"] = APPLIANCE_VIP
