from copy import deepcopy
from tests.dash.configs.privatelink_config import *

SIP = "10.3.0.1"
OUTBOUND_UNDERLAY_IP = "101.1.3.3"
ENI_MAC = "F4:93:9F:EF:C4:7D"

APPLIANCE_CONFIG = deepcopy(APPLIANCE_CONFIG)
APPLIANCE_CONFIG[f"DASH_APPLIANCE_TABLE:{APPLIANCE_ID}"]["sip"] = SIP
ENI_CONFIG = deepcopy(ENI_CONFIG)
ENI_CONFIG[f"DASH_ENI_TABLE:{ENI_ID}"]["mac_address"] = ENI_MAC
VNET_MAPPING_CONFIG = deepcopy(VNET_MAPPING_CONFIG)
VNET_MAPPING_CONFIG[f"DASH_VNET_MAPPING_TABLE:{VNET1}:{VNET_MAP_IP1}"]["underlay_ip"] = OUTBOUND_UNDERLAY_IP
