- header:
    model: mqm9700
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: 25.01.3932-014
- set:
    interface:
      swA1p1,swA2p1:
        link:
          connection-mode: ndr
        type: ib
    system:
      aaa:
        authentication:
          restrictions:
            fail-delay: 0
            lockout-state: disabled
        user:
          admin:
            password: $y$j9T$Uay927sQ.WFouaJb1uHpd/$Vn58Jt3rx4TElcI7KUYbtA/qQtK/qKM2qWy9J9wanF3
      date-time:
        timezone: Asia/Jerusalem
