PH1_INT_STAT = [
    "nvswitch_interface_pg_rx_frames",
    "nvswitch_interface_pg_rx_octet",
    "nvswitch_interface_tc_tx_ecn_marked_tc",
    "nvswitch_interface_tc_tx_frames",
    "nvswitch_interface_tc_tx_no_buffer_discard_uc",
    "nvswitch_interface_tc_tx_octet",
    "nvswitch_interface_tc_tx_queue",
    "nvswitch_interface_tc_tx_uc_frames",
    "nvswitch_interface_tc_tx_wred_discard"
]

PH1_ADD_STAT = [
    "nvswitch_interface_oper_state",
    "nvswitch_interface_performance_marked_packets"
]

PH1_DOT3_STAT = [
    "nvswitch_interface_dot3_stats_symbol_errors",
    "nvswitch_interface_dot3_stats_frame_too_longs",
    "nvswitch_interface_dot3_stats_fcs_errors",
    "nvswitch_interface_dot3_stats_deferred_transmissions",
    "nvswitch_interface_dot3_stats_carrier_sense_errors",
    "nvswitch_interface_dot3_out_pause_frames",
    "nvswitch_interface_dot3_in_pause_frames",
    "nvswitch_interface_dot3_control_in_unknown_opcodes"
]

PH1_HIST = [
    "nvswitch_histogram_interface_ingress_buffer",
    "nvswitch_histogram_interface_egress_buffer"
]

PH2_HIST = [
    "nvswitch_histogram_interface_latency",
    "nvswitch_histogram_interface_counter"
]

PH2_ADD_INT_STAT = [
    "nvswitch_interface_no_buffer_discard_mc",
    "nvswitch_interface_rx_buffer_almost_full",
    "nvswitch_interface_rx_buffer_full",
    "nvswitch_interface_rx_ebp",
    "nvswitch_interface_tx_ebp",
    "nvswitch_interface_tx_int_cksm_err",
    "nvswitch_interface_tx_wait"
]

PH2_INT_CAR_CHG = [
    "nvswitch_interface_carrier_up_changes_total",
    "nvswitch_interface_carrier_last_change_time_ms",
    "nvswitch_interface_carrier_down_changes_total",
    "nvswitch_interface_carrier_changes_total",
    "nvswitch_interface_mtu_bytes",
    "nvswitch_interface_info",
    "nvswitch_interface_iface_id",
    "nvswitch_interface_flags",
    "nvswitch_interface_proto_down"
]

PH2_INT_DISC_STATS = [
    "nvswitch_interface_discards_loopback_filter",
    "nvswitch_interface_discards_ingress_vlan_membership",
    "nvswitch_interface_discards_ingress_tx_link_down",
    "nvswitch_interface_discards_ingress_tag_frame_type",
    "nvswitch_interface_discards_ingress_policy_engine",
    "nvswitch_interface_discards_egress_vlan_membership",
    "nvswitch_interface_discards_egress_stp_filter",
    "nvswitch_interface_discards_egress_sll",
    "nvswitch_interface_discards_egress_policy_engine",
    "nvswitch_interface_discards_egress_hoq_stall",
    "nvswitch_interface_discards_egress_hoq"
]

PH2_INT_ETHER_STATS = [
    "nvswitch_interface_ether_stats_crc_align_errors",
    "nvswitch_interface_ether_stats_drop_events",
    "nvswitch_interface_ether_stats_fragments",
    "nvswitch_interface_ether_stats_jabbers",
    "nvswitch_interface_ether_stats_octets",
    "nvswitch_interface_ether_stats_oversize_pkts",
    "nvswitch_interface_ether_stats_undersize_pkts",
]

PH2_PKT_DIST_STATS = [
    "nvswitch_interface_tx_stats_pkts1024to1518octets",
    "nvswitch_interface_tx_stats_pkts128to255octets",
    "nvswitch_interface_tx_stats_pkts1519to2047octets",
    "nvswitch_interface_tx_stats_pkts2048to4095octets",
    "nvswitch_interface_tx_stats_pkts256to511octets",
    "nvswitch_interface_tx_stats_pkts4096to8191octets",
    "nvswitch_interface_tx_stats_pkts512to1023octets",
    "nvswitch_interface_tx_stats_pkts64octets",
    "nvswitch_interface_tx_stats_pkts65to127octets",
    "nvswitch_interface_tx_stats_pkts8192to10239octets",
    "nvswitch_interface_ether_stats_pkts",
    "nvswitch_interface_ether_stats_pkts1024to1518octets",
    "nvswitch_interface_ether_stats_pkts128to255octets",
    "nvswitch_interface_ether_stats_pkts1519to2047octets",
    "nvswitch_interface_ether_stats_pkts2048to4095octets",
    "nvswitch_interface_ether_stats_pkts256to511octets",
    "nvswitch_interface_ether_stats_pkts4096to8191octets",
    "nvswitch_interface_ether_stats_pkts512to1023octets",
    "nvswitch_interface_ether_stats_pkts64octets",
    "nvswitch_interface_ether_stats_pkts65to127octets",
    "nvswitch_interface_ether_stats_pkts8192to10239octets"
]

PH2_SW_PRIO_STATS = [
    "nvswitch_interface_sp_rx_discard",
    "nvswitch_interface_sp_rx_pause",
    "nvswitch_interface_sp_rx_pause_duration",
    "nvswitch_interface_sp_tx_pause",
    "nvswitch_interface_sp_tx_pause_duration"
]

PH2_CP_STATS = [
    "nvswitch_control_plane_tx_packets",
    "nvswitch_control_plane_tx_bytes",
    "nvswitch_control_plane_rx_packets",
    "nvswitch_control_plane_rx_bytes",
    "nvswitch_control_plane_rx_buffer_drops",
    "nvswitch_control_plane_trap_rx_packets",
    "nvswitch_control_plane_trap_rx_event_count",
    "nvswitch_control_plane_trap_rx_drop",
    "nvswitch_control_plane_trap_rx_bytes",
    "nvswitch_control_plane_trap_group_rx_packets",
    "nvswitch_control_plane_trap_group_rx_bytes",
    "nvswitch_control_plane_trap_group_pkt_violations"
]

PH2_NODE_MEM = [
    "node_memory_Zswapped_bytes",
    "node_memory_Zswap_bytes",
    "node_memory_WritebackTmp_bytes",
    "node_memory_Writeback_bytes",
    "node_memory_VmallocUsed_bytes",
    "node_memory_VmallocTotal_bytes",
    "node_memory_VmallocChunk_bytes",
    "node_memory_Unevictable_bytes",
    "node_memory_SwapTotal_bytes",
    "node_memory_SwapFree_bytes",
    "node_memory_SwapCached_bytes",
    "node_memory_SUnreclaim_bytes",
    "node_memory_SReclaimable_bytes",
    "node_memory_Slab_bytes",
    "node_memory_ShmemPmdMapped_bytes",
    "node_memory_ShmemHugePages_bytes",
    "node_memory_Shmem_bytes",
    "node_memory_SecPageTables_bytes",
    "node_memory_Percpu_bytes",
    "node_memory_PageTables_bytes",
    "node_memory_NFS_Unstable_bytes",
    "node_memory_Mlocked_bytes",
    "node_memory_MemTotal_bytes",
    "node_memory_MemFree_bytes",
    "node_memory_MemAvailable_bytes",
    "node_memory_Mapped_bytes",
    "node_memory_KReclaimable_bytes",
    "node_memory_KernelStack_bytes",
    "node_memory_Inactive_file_bytes",
    "node_memory_Inactive_bytes",
    "node_memory_Inactive_anon_bytes",
    "node_memory_Hugetlb_bytes",
    "node_memory_HugePages_Total",
    "node_memory_HugePages_Surp",
    "node_memory_HugePages_Rsvd",
    "node_memory_Hugepagesize_bytes",
    "node_memory_HugePages_Free",
    "node_memory_HardwareCorrupted_bytes",
    "node_memory_FilePmdMapped_bytes",
    "node_memory_FileHugePages_bytes",
    "node_memory_Dirty_bytes",
    "node_memory_DirectMap4k_bytes",
    "node_memory_DirectMap2M_bytes",
    "node_memory_DirectMap1G_bytes",
    "node_memory_Committed_AS_bytes",
    "node_memory_CommitLimit_bytes",
    "node_memory_Cached_bytes",
    "node_memory_Buffers_bytes",
    "node_memory_Bounce_bytes",
    "node_memory_AnonPages_bytes",
    "node_memory_AnonHugePages_bytes",
    "node_memory_Active_file_bytes",
    "node_memory_Active_bytes",
    "node_memory_Active_anon_bytes"
]

PH2_NODE_FILE = [
    "node_filesystem_size_bytes",
    "node_filesystem_readonly",
    "node_filesystem_free_bytes",
    "node_filesystem_files_free",
    "node_filesystem_files",
    "node_filesystem_device_error",
    "node_filesystem_avail_bytes"
]

PH2_NODE_DISK = [
    "node_disk_written_bytes_total",
    "node_disk_write_time_seconds_total",
    "node_disk_writes_merged_total",
    "node_disk_writes_completed_total",
    "node_disk_read_time_seconds_total",
    "node_disk_reads_merged_total",
    "node_disk_reads_completed_total",
    "node_disk_read_bytes_total",
    "node_disk_io_time_weighted_seconds_total",
    "node_disk_io_time_seconds_total",
    "node_disk_io_now",
    "node_disk_info",
    "node_disk_flush_requests_total",
    "node_disk_flush_requests_time_seconds_total",
    "node_disk_discard_time_seconds_total",
    "node_disk_discards_merged_total",
    "node_disk_discards_completed_total",
    "node_disk_discarded_sectors_total",
    "node_disk_ata_write_cache_enabled",
    "node_disk_ata_write_cache",
    "node_disk_ata_rotation_rate_rpm"
]

PH2_NODE_CPU = [
    "node_cpu_core_throttles_total",
    "node_cpu_guest_seconds_total",
    "node_cpu_package_throttles_total",
    "node_cpu_seconds_total"
]

PH2_PLAT_ENV = [
    "nvswitch_platform_environment_psu_power",
    "nvswitch_platform_environment_temp_state",
    "nvswitch_platform_environment_fan_dir",
    "nvswitch_platform_environment_psu_voltage",
    "nvswitch_platform_environment_fan_cur_speed",
    "nvswitch_platform_environment_fan_max",
    "nvswitch_platform_environment_fan_min",
    "nvswitch_platform_environment_fan_state",
    "nvswitch_platform_environment_temp_crit",
    "nvswitch_platform_environment_psu_capacity",
    "nvswitch_platform_environment_psu_current",
    "nvswitch_platform_environment_psu_state",
    "nvswitch_platform_environment_temp_current",
    "nvswitch_platform_environment_temp_max",
    "nvswitch_platform_environment_temp_min"
]

ALLOWED_EXTRAS = [
    "node_scrape_collector_duration_seconds",
    "scrape_duration_seconds",
    "scrape_samples_scraped",
    "node_exporter_build_info",
    "promhttp_metric_handler_errors_total",
    "node_scrape_collector_success",
    "scrape_samples_post_metric_relabeling",
    "scrape_series_added",
    "up"
]

PH3_ROUTING_STATS = [
    "nvrouting_bgp_peer_fsm_established_transitions",
    "nvrouting_bgp_peer_rib_adj_in_ipv4_unicast",
    "nvrouting_bgp_peer_rib_adj_in_ipv6_unicast",
    "nvrouting_bgp_peer_rib_adj_in_l2vpn_evpn",
    "nvrouting_bgp_peer_rx_updates",
    "nvrouting_bgp_peer_socket_in_queue",
    "nvrouting_bgp_peer_socket_out_queue",
    "nvrouting_bgp_peer_state",
    "nvrouting_bgp_peer_tx_updates",
    "nvrouting_rib_count",
    "nvrouting_rib_count_bgp",
    "nvrouting_rib_count_bgp_ipv6",
    "nvrouting_rib_count_connected",
    "nvrouting_rib_count_connected_ipv6",
    "nvrouting_rib_count_ipv6",
    "nvrouting_rib_count_kernel",
    "nvrouting_rib_count_kernel_ipv6",
    "nvrouting_rib_count_ospf",
    "nvrouting_rib_count_ospf_ipv6",
    "nvrouting_rib_count_pbr",
    "nvrouting_rib_count_pbr_ipv6",
    "nvrouting_rib_count_static",
    "nvrouting_rib_count_static_ipv6"
]

PH3_BUFF_STATS = [
    "nvswitch_interface_headroom_buffer_pg_curr_occupancy",
    "nvswitch_interface_headroom_buffer_pg_watermark",
    "nvswitch_interface_headroom_buffer_pg_watermark_recorded_max",
    "nvswitch_interface_headroom_pool_curr_occupancy",
    "nvswitch_interface_headroom_pool_watermark",
    "nvswitch_interface_headroom_pool_watermark_recorded_max",
    "nvswitch_interface_headroom_shared_buffer_curr_occupancy",
    "nvswitch_interface_headroom_shared_buffer_watermark",
    "nvswitch_interface_headroom_shared_buffer_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_mc_port_curr_occupancy",
    "nvswitch_interface_shared_buffer_mc_port_watermark",
    "nvswitch_interface_shared_buffer_mc_port_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_egress_pool_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_egress_pool_desc_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_egress_pool_desc_watermark",
    "nvswitch_interface_shared_buffer_port_egress_pool_desc_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_egress_pool_watermark",
    "nvswitch_interface_shared_buffer_port_egress_pool_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_ingress_pool_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_ingress_pool_desc_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_ingress_pool_desc_watermark",
    "nvswitch_interface_shared_buffer_port_ingress_pool_desc_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_ingress_pool_watermark",
    "nvswitch_interface_shared_buffer_port_ingress_pool_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_pg_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_pg_desc_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_pg_desc_watermark",
    "nvswitch_interface_shared_buffer_port_pg_desc_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_pg_watermark",
    "nvswitch_interface_shared_buffer_port_pg_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_tc_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_tc_desc_curr_occupancy",
    "nvswitch_interface_shared_buffer_port_tc_desc_watermark",
    "nvswitch_interface_shared_buffer_port_tc_desc_watermark_recorded_max",
    "nvswitch_interface_shared_buffer_port_tc_watermark",
    "nvswitch_interface_shared_buffer_port_tc_watermark_recorded_max",
    "nvswitch_shared_buffer_mc_sp_curr_occupancy",
    "nvswitch_shared_buffer_mc_sp_watermark",
    "nvswitch_shared_buffer_mc_sp_watermark_recorded_max",
    "nvswitch_shared_buffer_pool_curr_occupancy",
    "nvswitch_shared_buffer_pool_watermark",
    "nvswitch_shared_buffer_pool_watermark_recorded_max"
]

PH3_PHY_STATS = [
    "nvswitch_interface_phy_stats_phy_corrected_bits",
    "nvswitch_interface_phy_stats_phy_effective_errors",
    "nvswitch_interface_phy_stats_phy_raw_errors",
    "nvswitch_interface_phy_stats_phy_received_bits",
    "nvswitch_interface_phy_stats_phy_symbol_errors",
    "nvswitch_interface_phy_stats_raw_ber",
    "nvswitch_interface_phy_stats_time_since_last_clear"
]

PH3_EXTRAS = [
    "node_forks_total",
    "node_time_zone_offset_seconds",
    "nvswitch_interface_number_of_lanes",
    "node_procs_running",
    "node_time_clocksource_current_info",
    "node_boot_time_seconds",
    "node_time_seconds",
    "node_intr_total",
    "node_procs_blocked",
    "node_time_clocksource_available_info",
    "node_context_switches_total",
    "node_os_info",
    "node_os_version",
    "nvswitch_interface_oper_aggregate_speed"
]

PH4_EXTRAS = [
    'nvswitch_interface_if_in_discards',
    'nvswitch_interface_if_in_errors',
    'nvswitch_interface_if_in_ucast_pkts',
    'nvswitch_interface_if_out_broadcast_pkts',
    'nvswitch_interface_if_out_discards',
    'nvswitch_interface_if_out_errors',
    'nvswitch_interface_if_out_multicast_pkts',
    'nvswitch_interface_if_out_octets',
    'nvswitch_interface_if_out_ucast_pkts',
    'nvswitch_interface_phy_layer_fec_block_state_count',
    'nvswitch_interface_phy_layer_fec_per_lane_corrections',
    'nvswitch_interface_phy_layer_time_since_last_clear',
    'nvswitch_interface_phy_stats_effective_ber',
    'nvswitch_interface_phy_stats_symbol_ber',
    'nvswitch_interface_shared_buffer_port_tc_time_since_clear',
    'nvswitch_interface_shared_buffer_port_pg_time_since_clear',
    'nvswitch_interface_802_dot3_a_frames_transmitted_ok'
]

PH4_ROUTING_STATS = [
    "nvrouting_bgp_peer_fsm_established_transitions",
    "nvrouting_bgp_peer_rib_adj_in",
    "nvrouting_bgp_peer_rib_adj_in_installed",
    "nvrouting_bgp_peer_rib_adj_out_advertised",
    "nvrouting_bgp_peer_rx_updates",
    "nvrouting_bgp_peer_socket_in_queue",
    "nvrouting_bgp_peer_socket_out_queue",
    "nvrouting_bgp_peer_state",
    "nvrouting_bgp_peer_total_msgs_recvd",
    "nvrouting_bgp_peer_total_msgs_sent",
    "nvrouting_bgp_peer_tx_updates",
    "nvrouting_rib_count",
    "nvrouting_rib_nhg_count"
]

PH4_SOFTWARE_STATS = [
    'nvswitch_systemd_unit_cpu_usage_seconds',
    'nvswitch_systemd_unit_exe_path',
    'nvswitch_systemd_unit_main_pid',
    'nvswitch_systemd_unit_memory_usage_bytes',
    'nvswitch_systemd_unit_restart',
    'nvswitch_systemd_unit_running',
    'nvswitch_systemd_unit_start_time_seconds',
    'nvswitch_systemd_unit_state',
    'nvswitch_systemd_unit_threads',
    'nvswitch_systemd_unit_uptime_seconds',
    'nvswitch_systemd_unit_process_context_switches',
    'nvswitch_systemd_unit_process_cpu_usage_seconds',
    'nvswitch_systemd_unit_processes',
    'nvswitch_systemd_unit_process_parent_pid',
    'nvswitch_systemd_unit_process_resident_memory_usage_bytes',
    'nvswitch_systemd_unit_process_shared_memory_usage_bytes',
    'nvswitch_systemd_unit_process_virtual_memory_usage_bytes',
    'nvswitch_systemd_unit_process_start_time_seconds',
    'nvswitch_systemd_unit_process_state',
    'nvswitch_systemd_unit_process_subprocesses',
    'nvswitch_systemd_unit_process_threads'
]

PH4_LLDP_STATS = [
    'nvswitch_lldp_chassis_info',
    'nvswitch_lldp_chassis_capabilities',
    'nvswitch_lldp_neighbor_age',
    'nvswitch_lldp_neighbor_capabilities',
    'nvswitch_lldp_neighbor_info',
    'nvswitch_lldp_neighbor_ttl',
    'nvswitch_lldp_neighbor_management_address_info'
]

PH4_ADAPTIVE_ROUTING_STATS = [
    'nvswitch_ar_congestion_changes'
]

PH4_TRANSCEIVER_INFO_ALL = [
    'nvswitch_platform_transceiver_info',
    'nvswitch_platform_transceiver_vendor_info'
]

PH4_TRANSCEIVER_INFO_FIBER_ONLY = [
    'nvswitch_platform_transceiver_temperature',
    'nvswitch_platform_tranceiver_temperature_alarm',
    'nvswitch_platform_tranceiver_temperature_threshold_info',
    'nvswitch_platform_tranceiver_voltage',
    'nvswitch_platform_tranceiver_voltage_alarm',
    'nvswitch_platform_tranceiver_voltage_threshold_info',
    'nvswitch_platform_transceiver_channel_power',
    'nvswitch_platform_transceiver_channel_power_alarm',
    'nvswitch_platform_transceiver_channel_power_threshold_info',
    'nvswitch_platform_transceiver_tx_bias_current',
    'nvswitch_platform_transceiver_tx_bias_current_alarm',
    'nvplatform_transceiver_tx_bias_current_threshold_info'
]

# OTEL transceiver threshold metric names
TRANSCEIVER_OTEL_METRICS = [
    'nvswitch_platform_transceiver_module_temperature_threshold_info',
    'nvswitch_platform_transceiver_supply_voltage_threshold_info',
    'nvswitch_platform_transceiver_output_power_threshold_info',
    'nvswitch_platform_transceiver_input_power_threshold_info',
    'nvswitch_platform_transceiver_laser_bias_current_threshold_info',
]

PH4_ADDITIONAL_NODE_STATS = [
    'node_hwmon_in_max_alarm_volts',
    'node_timex_maxerror_seconds',
    'node_network_dormant',
    'node_netstat_Udp_InErrors',
    'node_sockstat_UDP_mem_bytes',
    'node_network_receive_packets_total',
    'node_timex_frequency_adjustment_ratio',
    'node_hwmon_power_watt',
    'node_cpu_scaling_frequency_hertz',
    'node_hwmon_in_min_volts',
    'node_schedstat_waiting_seconds_total',
    'node_sockstat_RAW_inuse',
    'node_sockstat_TCP_alloc',
    'node_hwmon_temp_max_alarm_celsius',
    'node_hwmon_in_min_alarm_volts',
    'node_network_receive_frame_total',
    'node_netstat_Tcp_OutRsts',
    'node_dmi_info',
    'node_hwmon_in_lcrit_alarm_volts',
    'node_netstat_Tcp_InSegs',
    'node_nf_conntrack_stat_invalid',
    'node_hwmon_pwm',
    'node_hwmon_curr_crit_alarm_amps',
    'node_netstat_IpExt_OutOctets',
    'node_cooling_device_max_state',
    'node_sockstat_TCP_mem',
    'node_timex_pps_error_total',
    'node_hwmon_temp_min_alarm_celsius',
    'node_hwmon_power_rated_max_watt',
    'node_network_device_id',
    'node_hwmon_sensor_label',
    'node_netstat_TcpExt_ListenOverflows',
    'node_netstat_Icmp6_InMsgs',
    'node_netstat_Udp6_InErrors',
    'node_sockstat_UDP6_inuse',
    'node_network_receive_fifo_total',
    'node_netstat_Icmp6_InErrors',
    'node_hwmon_curr_lcrit_alarm_amps',
    'node_hwmon_power_crit_alarm_watt',
    'node_netstat_Tcp_RetransSegs',
    'node_network_transmit_colls_total',
    'node_timex_sync_status',
    'node_pressure_memory_waiting_seconds_total',
    'node_softnet_times_squeezed_total',
    'node_hwmon_temp_rated_max_celsius',
    'node_network_flags',
    'node_timex_estimated_error_seconds',
    'node_netstat_Udp_SndbufErrors',
    'node_sockstat_UDP_inuse',
    'node_nf_conntrack_stat_search_restart',
    'node_sockstat_FRAG_inuse',
    'node_timex_offset_seconds',
    'node_filefd_allocated',
    'node_netstat_Tcp_InErrs',
    'node_netstat_IpExt_InOctets',
    'node_network_carrier_down_changes_total',
    'node_hwmon_in_max_volts',
    'node_sockstat_TCP6_inuse',
    'node_hwmon_temp_celsius',
    'node_netstat_Icmp6_OutMsgs',
    'node_network_speed_bytes',
    'node_hwmon_temp_highest_celsius',
    'node_network_carrier_changes_total',
    'node_udp_queues',
    'node_sockstat_FRAG6_inuse',
    'node_hwmon_in_rated_max_volts',
    'node_vmstat_pgmajfault',
    'node_nf_conntrack_stat_early_drop',
    'node_network_name_assign_type',
    'node_hwmon_fan_fault',
    'node_netstat_Udp6_SndbufErrors',
    'node_nf_conntrack_stat_insert_failed',
    'node_sockstat_TCP_mem_bytes',
    'node_hwmon_temp_max_celsius',
    'node_network_carrier',
    'node_nf_conntrack_entries_limit',
    'node_sockstat_FRAG6_memory',
    'node_network_up',
    'node_timex_pps_shift_seconds',
    'node_network_iface_link',
    'node_network_iface_id',
    'node_sockstat_FRAG_memory',
    'node_uname_info',
    'node_netstat_Tcp_OutSegs',
    'node_vmstat_pswpout',
    'node_textfile_scrape_error',
    'node_network_receive_drop_total',
    'node_netstat_UdpLite6_InErrors',
    'node_network_receive_bytes_total',
    'node_network_transmit_drop_total',
    'node_netstat_Tcp_ActiveOpens',
    'node_hwmon_in_crit_volts',
    'node_hwmon_fan_target_rpm',
    'node_sockstat_UDP_mem',
    'node_netstat_Icmp_OutMsgs',
    'node_netstat_TcpExt_SyncookiesFailed',
    'node_netstat_TcpExt_SyncookiesRecv',
    'node_hwmon_temp_crit_celsius',
    'node_hwmon_in_rated_min_volts',
    'node_network_receive_multicast_total',
    'node_network_carrier_up_changes_total',
    'node_network_transmit_bytes_total',
    'node_netstat_Udp6_InDatagrams',
    'node_vmstat_pgfault',
    'node_sockstat_TCP_tw',
    'node_netstat_TcpExt_TCPTimeouts',
    'node_timex_pps_frequency_hertz',
    'node_hwmon_temp_max_hyst_celsius',
    'node_timex_pps_jitter_seconds',
    'node_edac_csrow_uncorrectable_errors_total',
    'node_pressure_io_stalled_seconds_total',
    'node_hwmon_in_volts',
    'node_hwmon_temp_crit_alarm_celsius',
    'node_load5',
    'node_cpu_scaling_frequency_min_hertz',
    'node_hwmon_curr_amps',
    'node_netstat_Udp_InDatagrams',
    'node_timex_pps_calibration_total',
    'node_softnet_processed_total',
    'node_hwmon_power_alarm',
    'node_vmstat_pgpgout',
    'node_nf_conntrack_stat_insert',
    'node_softnet_dropped_total',
    'node_cpu_scaling_frequency_max_hertz',
    'node_hwmon_temp_fault',
    'node_cpu_frequency_min_hertz',
    'node_network_transmit_errs_total',
    'node_edac_correctable_errors_total',
    'node_hwmon_chip_names',
    'node_sockstat_RAW6_inuse',
    'node_timex_pps_jitter_total',
    'node_timex_tai_offset_seconds',
    'node_hwmon_curr_rated_max_amps',
    'node_hwmon_in_lcrit_volts',
    'node_network_mtu_bytes',
    'node_hwmon_temp_lcrit_alarm_celsius',
    'node_nf_conntrack_stat_ignore',
    'node_netstat_TcpExt_SyncookiesSent',
    'node_schedstat_running_seconds_total',
    'node_netstat_Ip6_OutOctets',
    'node_nf_conntrack_stat_drop',
    'node_thermal_zone_temp',
    'node_pressure_memory_stalled_seconds_total',
    'node_timex_tick_seconds',
    'node_network_iface_link_mode',
    'node_network_protocol_type',
    'node_entropy_available_bits',
    'node_hwmon_curr_max_alarm_amps',
    'node_vmstat_pswpin',
    'node_sockstat_UDPLITE6_inuse',
    'node_netstat_Icmp_InErrors',
    'node_nf_conntrack_stat_found',
    'node_entropy_pool_size_bits',
    'node_nf_conntrack_entries',
    'node_netstat_Udp_OutDatagrams',
    'node_timex_pps_stability_exceeded_total',
    'node_arp_entries',
    'node_netstat_Tcp_CurrEstab',
    'node_pressure_cpu_waiting_seconds_total',
    'node_hwmon_power_crit_watt',
    'node_network_receive_compressed_total',
    'node_sockstat_UDPLITE_inuse',
    'node_netstat_TcpExt_ListenDrops',
    'node_hwmon_fan_rpm',
    'node_timex_status',
    'node_netstat_Ip_Forwarding',
    'node_sockstat_TCP_orphan',
    'node_netstat_Udp6_NoPorts',
    'node_timex_loop_time_constant',
    'node_hwmon_power_cap_watt',
    'node_network_info',
    'node_netstat_Udp6_OutDatagrams',
    'node_network_transmit_fifo_total',
    'node_hwmon_fan',
    'node_hwmon_temp_min_celsius',
    'node_hwmon_temp_emergency_celsius',
    'node_hwmon_curr_crit_amps',
    'node_vmstat_pgpgin',
    'node_network_receive_errs_total',
    'node_netstat_Ip6_InOctets',
    'node_hwmon_temp_lcrit_celsius',
    'node_netstat_Tcp_PassiveOpens',
    'node_netstat_Udp_RcvbufErrors',
    'node_network_receive_nohandler_total',
    'node_timex_pps_stability_hertz',
    'node_sockstat_sockets_used',
    'node_edac_csrow_correctable_errors_total',
    'node_hwmon_curr_max_amps',
    'node_network_transmit_compressed_total',
    'node_hwmon_fan_alarm',
    'node_pressure_io_waiting_seconds_total',
    'node_schedstat_timeslices_total',
    'node_hwmon_power_cap_alarm_watt',
    'node_filefd_maximum',
    'node_network_transmit_packets_total',
    'node_netstat_Udp_NoPorts',
    'node_hwmon_in_crit_alarm_volts',
    'node_load1',
    'node_edac_uncorrectable_errors_total',
    'node_sockstat_TCP_inuse',
    'node_hwmon_temp_emergency_alarm_celsius',
    'node_network_transmit_queue_length',
    'node_cpu_frequency_max_hertz',
    'node_hwmon_power_max_alarm_watt',
    'node_load15',
    'node_netstat_Icmp_InMsgs',
    'node_hwmon_power_max_watt',
    'node_selinux_enabled',
    'node_netstat_TcpExt_TCPSynRetrans',
    'node_netstat_Udp6_RcvbufErrors',
    'node_hwmon_curr_lcrit_amps',
    'node_cooling_device_cur_state',
    'node_network_address_assign_type',
    'node_netstat_UdpLite_InErrors',
    'node_network_net_dev_group',
    'node_vmstat_oom_kill',
    'node_network_transmit_carrier_total'
]

PH5_ADDITIONS = [
    'nvswitch_interface_type',
    'nvswitch_interface_hw_address_info',
    'nvswitch_platform_environment_temp_crit_lo',
    'nvswitch_platform_environment_psu_input_voltage',
    'nvswitch_platform_environment_psu_input_current',
    'nvswitch_systemd_unit_process_cpu_usage_system_seconds',
    'nvswitch_systemd_unit_process_info',
    'nvswitch_systemd_unit_process_cpu_usage_user_seconds',
    'nvswitch_platform_transceiver_ethernet_pmd',
    'nvswitch_platform_info_last_reboot_time',
    'nvswitch_platform_info_last_reboot_reason',
    'nvswitch_lldp_interface_enabled',
    'nvswitch_platform_info_firmware_version',
    'nvswitch_interface_phy_rs_fec_histogram',
    'nvswitch_interface_shared_buffer_port_tc_watermark_recorded_max_bytes',
    'nvswitch_interface_shared_buffer_port_pg_watermark_recorded_max_timestamp',
    'nvswitch_interface_headroom_shared_buffer_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_egress_pool_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_pg_desc_watermark_recorded_max_timestamp',
    'nvswitch_shared_buffer_pool_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_tc_desc_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_ingress_pool_desc_watermark_recorded_max_timestamp',
    'nvswitch_shared_buffer_mc_sp_watermark_recorded_max_timestamp',
    'nvswitch_interface_headroom_buffer_pg_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_egress_pool_desc_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_ingress_pool_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_port_tc_watermark_recorded_max_timestamp',
    'nvswitch_interface_shared_buffer_mc_port_watermark_recorded_max_timestamp',
    'nvswitch_interface_headroom_pool_watermark_recorded_max_timestamp',
    'nvswitch_interface_autoneg_enabled',
    'nvswitch_interface_autoneg_adv_speed'
]

PH5_ROUTING_STATS = [
    'nvrouting_bgp_peer_last_established',
    'nvrouting_bgp_peer_info',
    'nvrouting_bgp_peer_as',
    'nvrouting_bgp_peer_local_as'
]

CL_514_AI_ETHERNET_STATS = [
    'nvswitch_ar_congestion_changes',
    'nvswitch_srv6_no_sid_drops',
    'nvswitch_srv6_in_pkts',
    'nvswitch_qos_trimmed_unicast_pkts'
]

CL_515_AI_ETHERNET_STATS = [
    'nvswitch_interface_trimmed_unicast_pkts',
    'nvswitch_interface_trimmed_tx_unicast_pkts',
    'nvswitch_interface_tc_trimmed_unicast_pkts',
]

PH6_ADDITIONAL_NODE_STATS = [
    'node_netstat_Ip_InReceives',
    'node_netstat_Ip_InAddrErrors',
    'node_netstat_Ip_InDelivers',
    'node_netstat_Ip6_InReceives',
    'node_netstat_Ip6_InAddrErrors',
    'node_netstat_Ip6_InDelivers'
]

CL_515_ROUTING_STATS = [
    'nvrouting_bgp_peer_graceful_shutdown',
    'nvrouting_bgp_peer_last_established',
    'nvrouting_bgp_peer_info',
    'nvrouting_bgp_peer_as',
    'nvrouting_bgp_peer_local_as',
    'nvrouting_bgp_peer_fsm_established_transitions',
    'nvrouting_bgp_peer_rib_adj_in',
    'nvrouting_bgp_peer_rib_adj_in_installed',
    'nvrouting_bgp_peer_rib_adj_out_advertised',
    'nvrouting_bgp_peer_rx_updates',
    'nvrouting_bgp_peer_socket_in_queue',
    'nvrouting_bgp_peer_socket_out_queue',
    'nvrouting_bgp_peer_state',
    'nvrouting_bgp_peer_total_msgs_recvd',
    'nvrouting_bgp_peer_total_msgs_sent',
    'nvrouting_bgp_peer_tx_updates',
    'nvrouting_rib_count',
    'nvrouting_rib_total_count',
    'nvrouting_rib_nhg_count'
]

CL_515_ADDITIONAL_INT_STATS = [
    'nvswitch_interface_ether_stats_broadcast_pkts',
    'nvswitch_interface_ether_stats_multicast_pkts'
]

PH6_ACL_STATS = [
    'nvswitch_acl_interface_matched_pkts',
    'nvswitch_acl_interface_matched_bytes',
    'nvswitch_acl_set_ipv4_info',
    'nvswitch_acl_set_ipv6_info',
    'nvswitch_acl_set_l2_info',
    'nvswitch_acl_set_l4_info'
]

PH6_DOT1X_STATS = [
    'nvswitch_dot1x_system_info',
    'nvswitch_dot1x_radius_client_info',
    'nvswitch_dot1x_radius_server_info',
    'nvswitch_dot1x_supplicant_summary',
    'nvswitch_dot1x_supplicant_eapol_counters',
    'nvswitch_dot1x_interface_info',
    'nvswitch_dot1x_supplicant_status',
    'nvswitch_dot1x_ipv6_profile_info',
    'nvswitch_dot1x_ipv6_profile_property_info',
    'nvswitch_dot1x_ipv6_profile_summary',
    'nvswitch_dot1x_reauth_timeouts'
]

# CL 5.16+ QoS Buffer Metrics from QosBufferXPaths
# These metrics correspond to the new buffer telemetry xpaths added in CL 5.16+
# Only these 17 metrics are supported in CL 5.16
CL_516_QOS_BUFFER_METRICS = [
    'nvswitch_interface_shared_buffer_port_pg_desc_time_since_clear',
    'nvswitch_interface_shared_buffer_port_tc_desc_time_since_clear',
    'nvswitch_interface_shared_buffer_port_ingress_pool_time_since_clear',
    'nvswitch_interface_shared_buffer_port_ingress_pool_desc_time_since_clear',
    'nvswitch_interface_shared_buffer_port_egress_pool_time_since_clear',
    'nvswitch_interface_shared_buffer_port_egress_pool_desc_time_since_clear',
    'nvswitch_interface_shared_buffer_mc_port_time_since_clear',
    'nvswitch_shared_buffer_mc_sp_time_since_clear',
    'nvswitch_shared_buffer_pool_time_since_clear',
    'nvswitch_interface_headroom_pool_time_since_clear',
    'nvswitch_interface_headroom_buffer_pg_time_since_clear',
    'nvswitch_interface_headroom_shared_buffer_time_since_clear',
    'nvswitch_buffer_cell_size_bytes',
    'nvswitch_shared_buffer_pool_desc_curr_occupancy',
    'nvswitch_shared_buffer_pool_desc_watermark',
    'nvswitch_shared_buffer_pool_desc_watermark_recorded_max',
    'nvswitch_shared_buffer_pool_desc_watermark_recorded_max_timestamp',
    'nvswitch_shared_buffer_pool_desc_time_since_clear'
]

CL_517_ADDITIONAL_PLATFORM_STATS = [
    'nvswitch_platform_info_hw_details',
]

# CL 5.17+ Control Plane Software Stats
CL_517_CP_NETSTAT_METRICS = [
    'node_netstat_Icmp_InDestUnreachs',
    'node_netstat_Tcp_OutRsts',
    'node_netstat_Ip6_OutRequests',
    'node_netstat_IpExt_InECT1Pkts',
    'node_netstat_Icmp6_OutEchos',
    'node_netstat_Ip6_OutMcastOctets',
    'node_netstat_Tcp_PassiveOpens',
    'node_netstat_IpExt_OutMcastOctets',
    'node_netstat_Ip_OutDiscards',
    'node_netstat_Icmp6_InNeighborAdvertisements',
    'node_netstat_Ip6_OutOctets',
    'node_netstat_Tcp_AttemptFails',
    'node_netstat_Udp6_NoPorts',
    'node_netstat_Ip_InDiscards',
    'node_netstat_Tcp_RetransSegs',
    'node_netstat_Ip_InHdrErrors',
    'node_netstat_Icmp6_OutEchoReplies',
    'node_netstat_Ip6_OutForwDatagrams',
    'node_netstat_Icmp_InTimeExcds',
    'node_netstat_Icmp6_InNeighborSolicits',
    'node_netstat_IpExt_OutMcastPkts',
    'node_netstat_Icmp6_OutRedirects',
    'node_netstat_IpExt_InMcastPkts',
    'node_netstat_Tcp_CurrEstab',
    'node_netstat_Ip6_InTruncatedPkts',
    'node_netstat_Ip_InUnknownProtos',
    'node_netstat_IpExt_OutBcastPkts',
    'node_netstat_IpExt_InOctets',
    'node_netstat_Tcp_ActiveOpens',
    'node_netstat_Tcp_InErrs',
    'node_netstat_IpExt_OutOctets',
    'node_netstat_Ip6_OutMcastPkts',
    'node_netstat_Icmp_OutEchoReps',
    'node_netstat_TcpExt_TCPSynRetrans',
    'node_netstat_IpExt_InECT0Pkts',
    'node_netstat_Tcp_InSegs',
    'node_netstat_Icmp6_OutNeighborSolicits',
    'node_netstat_Icmp_InEchos',
    'node_netstat_Ip6_InNoRoutes',
    'node_netstat_Ip_FragFails',
    'node_netstat_Icmp6_InEchoReplies',
    'node_netstat_Udp6_InDatagrams',
    'node_netstat_Icmp_OutTimeExcds',
    'node_netstat_Icmp_OutErrors',
    'node_netstat_Ip6_InDiscards',
    'node_netstat_Icmp6_InTimeExcds',
    'node_netstat_Icmp6_OutErrors',
    'node_netstat_Ip6_InECT0Pkts',
    'node_netstat_Icmp_OutRedirects',
    'node_netstat_Ip6_OutDiscards',
    'node_netstat_Udp_OutDatagrams',
    'node_netstat_Ip6_InECT1Pkts',
    'node_netstat_Udp6_SndbufErrors',
    'node_netstat_Icmp6_InRouterSolicits',
    'node_netstat_Ip6_FragOKs',
    'node_netstat_Icmp_OutMsgs',
    'node_netstat_Tcp_EstabResets',
    'node_netstat_Icmp_InEchoReps',
    'node_netstat_Icmp_InMsgs',
    'node_netstat_Udp6_InErrors',
    'node_netstat_Icmp_OutDestUnreachs',
    'node_netstat_Ip6_InUnknownProtos',
    'node_netstat_Udp6_OutDatagrams',
    'node_netstat_Ip6_ReasmReqds',
    'node_netstat_Ip_ReasmReqds',
    'node_netstat_IpExt_InTruncatedPkts',
    'node_netstat_Ip_FragOKs',
    'node_netstat_Icmp6_InMsgs',
    'node_netstat_Icmp6_OutRouterAdvertisements',
    'node_netstat_Ip_FragCreates',
    'node_netstat_Icmp6_InEchos',
    'node_netstat_Icmp6_InErrors',
    'node_netstat_Udp6_RcvbufErrors',
    'node_netstat_Ip6_InCEPkts',
    'node_netstat_Ip6_InMcastPkts',
    'node_netstat_TcpExt_ListenDrops',
    'node_netstat_Ip_ReasmFails',
    'node_netstat_IpExt_InNoECTPkts',
    'node_netstat_Ip6_InMcastOctets',
    'node_netstat_Ip6_InNoECTPkts',
    'node_netstat_IpExt_InCEPkts',
    'node_netstat_Ip6_ReasmOKs',
    'node_netstat_TcpExt_ListenOverflows',
    'node_netstat_Icmp6_InDestUnreachs',
    'node_netstat_Icmp6_InRouterAdvertisements',
    'node_netstat_IpExt_InNoRoutes',
    'node_netstat_Udp_SndbufErrors',
    'node_netstat_TcpExt_TCPTimeouts',
    'node_netstat_Icmp_InErrors',
    'node_netstat_Udp_InErrors',
    'node_netstat_Ip6_ReasmFails',
    'node_netstat_Icmp6_OutTimeExcds',
    'node_netstat_Udp_RcvbufErrors',
    'node_netstat_Icmp6_OutRouterSolicits',
    'node_netstat_Icmp_OutEchos',
    'node_netstat_Udp_InDatagrams',
    'node_netstat_Ip_OutNoRoutes',
    'node_netstat_Udp_NoPorts',
    'node_netstat_Ip6_FragCreates',
    'node_netstat_Ip6_OutNoRoutes',
    'node_netstat_Ip_ForwDatagrams',
    'node_netstat_IpExt_InBcastPkts',
    'node_netstat_Ip_ReasmOKs',
    'node_netstat_Icmp_InRedirects',
    'node_netstat_IpExt_InMcastOctets',
    'node_netstat_Icmp6_InRedirects',
    'node_netstat_Ip_OutRequests',
    'node_netstat_Ip6_InOctets',
    'node_netstat_Ip6_FragFails',
    'node_netstat_Tcp_OutSegs',
    'node_netstat_Icmp6_OutMsgs',
    'node_netstat_Icmp6_OutDestUnreachs',
    'node_netstat_Icmp6_OutNeighborAdvertisements',
    'node_netstat_Ip6_InHdrErrors',
]

CL_517_ADDITIONAL = [
    'nvswitch_interface_if_in_octets',  # Issue 4909312
]

CL_517_ADDITIONAL_PHY = [
    'nvswitch_interface_phy_link_down_opcode'
]

CL_517_LINK_DEBOUNCE_STATS = [
    'nvswitch_interface_link_debounce_timer_expirations',
    'nvswitch_interface_link_debounce_timer_cancellations',
    'nvswitch_interface_link_debounce_received_events',
    'nvswitch_interface_link_debounce_ignored_events',
]
