---
  - mlx-2410b-01
  - moose-42
  - mtvr-moose-01
  - mtvr-moose-02
  - mtvr-moose-03
  - mtvr-moose-04
  - mtvr-moose-05
  - mtvr-moose-06
  - mtvr-moose-07
  - mtvr-moose-08
  - mtvr-moose-09
  - mtvr-moose-10
  - mtvr-moose-16
  - mtvr-moose-17
  - mtvr-moose-18
  - mtvr-bison-133
  - r-bison-11
  - r-bison-12
  - bison-1211
  - bison-1212
  - nvidia_common
  - nvidia
  - r-anaconda-15
  - r-anaconda-51
  - r-anaconda-70
  - r-anaconda-71
  - r-anaconda-75
  - r-anaconda-76
  - r-anaconda-77
  - r-leopard-32
  - r-leopard-41
  - r-leopard-42
  - r-leopard-43
  - r-leopard-44
  - r-leopard-45
  - r-leopard-50
  - r-leopard-56
  - r-lionfish-07
  - r-lionfish-13
  - r-lionfish-14
  - r-lionfish-16
  - r-moose-02
  - r-panther-03
  - r-panther-13
  - r-panther-16
  - r-panther-17
  - r-panther-19
  - r-panther-20
  - r-panther-22
  - r-panther-36
  - r-tigon-15
  - r-tigon-17
  - mtvr-tigon-05
  - mtvr-tigon-06
  - mtvr-tigon-07
  - r-gaur-04
  - mtvr-bobcat-05
  - mtvr-bobcat-06
  - mtvr-bobcat-07
  - mtvr-bobcat-08
  - bobcat-10
  - example_ixia
