TPM_DIR = '/host/tpm'

AIK_FILENAME = 'IAK.crt'
AIK_FILE_PATH = f'{TPM_DIR}/{AIK_FILENAME}'

OAIK_FILENAME = 'oIAK.crt'
OAIK_FILE_PATH = f'{TPM_DIR}/{OAIK_FILENAME}'
OIAK_DUMMY_CERT_PATH = '/auto/sw_system_project/NVOS_INFRA/oiak/oiak.txt'

AIK_PEM_FILENAME = AIK_FILENAME.replace('crt', 'pem')

TPM_DIR_CONTENT_AFTER_INIT = {AIK_FILENAME, 'IAK.ctx', 'IAK.der', 'AIK.tmp'}

QUOTE_FILENAME = 'quotes.json'
QUOTE_FILE_PATH = f'{TPM_DIR}/{QUOTE_FILENAME}'

REMOTE_PATH = '/tmp'
REMOTE_SCP_URL = 'scp://{}:{}@{}' + REMOTE_PATH + '/{}'

VALID_PCRS_PARAM = '0,4,7'
VALID_NONCE_PARAM = '1234ABCD'

SHA256 = 'sha256'
SHA384 = 'sha384'
KNOWN_ALGORITHMS = {SHA256, SHA384}
SUPPORTED_ALGORITHMS = {SHA384}
UNSUPPORTED_ALGORITHMS = KNOWN_ALGORITHMS - SUPPORTED_ALGORITHMS

MAX_BITS_NONCE = 512
MAX_CHARS_NONCE = MAX_BITS_NONCE // 4
