# secret key for clients that configure this server
key = "mysecretkey"
 
# path to accounting file
accounting file = /var/log/tac.acct
 
# Users
user = tacadm {
    name = "Admin User"
    member = "admin_group"
    pap = cleartext tacadm_pap
    chap = cleartext tacadm_chap
    login = cleartext tacadm_login
}

user = tacmon {
    name = "Monitor User"
    member = "monitor_group"
    pap = cleartext tacmon_pap
    chap = cleartext tacmon_chap
    login = cleartext tacmon_login
}
 
# Groups
group = admin_group {
    default service = permit
    service = exec {
        default attribute = permit
        priv-lvl = 15
    }
}

group = monitor_group {
    default service = permit
    service = exec {
        default attribute = permit
        priv-lvl = 7
    }
}