# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nmx-telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nmx-telemetry.proto\"(\n\nKeyValPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"j\n\x0cServerHeader\x12\x13\n\x0b\x64omain_uuid\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_uuid\x18\x02 \x01(\t\x12\x0f\n\x07\x61pp_ver\x18\x03 \x01(\t\x12\"\n\nreturnCode\x18\x04 \x01(\x0e\x32\x0e.ST_ReturnCode\"|\n\x0b\x43lientHello\x12\x11\n\tgatewayId\x18\x01 \x01(\t\x12,\n\rmajor_version\x18\x02 \x01(\x0e\x32\x15.ProtoMsgMajorVersion\x12,\n\rminor_version\x18\x03 \x01(\x0e\x32\x15.ProtoMsgMinorVersion\"\xe2\x01\n\x0bServerHello\x12#\n\x0cserverHeader\x18\x01 \x01(\x0b\x32\r.ServerHeader\x12#\n\x0e\x63omponents_ver\x18\x02 \x03(\x0b\x32\x0b.KeyValPair\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t\x12\x17\n\x0fhost_os_details\x18\x04 \x01(\t\x12,\n\rmajor_version\x18\x05 \x01(\x0e\x32\x15.ProtoMsgMajorVersion\x12,\n\rminor_version\x18\x06 \x01(\x0e\x32\x15.ProtoMsgMinorVersion*Y\n\x14ProtoMsgMajorVersion\x12$\n PROTO_MSG_MAJOR_VERSION_UNDEFIND\x10\x00\x12\x1b\n\x17PROTO_MSG_MAJOR_VERSION\x10\x01*Y\n\x14ProtoMsgMinorVersion\x12$\n PROTO_MSG_MINOR_VERSION_UNDEFIND\x10\x00\x12\x1b\n\x17PROTO_MSG_MINOR_VERSION\x10\x01*\x85\x02\n\rST_ReturnCode\x12\x10\n\x0cST_UNDEFINED\x10\x00\x12\x0e\n\nST_SUCCESS\x10\x01\x12\x0f\n\x0bST_BADPARAM\x10\x02\x12\x14\n\x10ST_GENERIC_ERROR\x10\x03\x12\x14\n\x10ST_NOT_SUPPORTED\x10\x04\x12\x14\n\x10ST_UNINITIALIZED\x10\x05\x12\x0e\n\nST_TIMEOUT\x10\x06\x12\x17\n\x13ST_VERSION_MISMATCH\x10\x07\x12\r\n\tST_IN_USE\x10\x08\x12\x15\n\x11ST_NOT_CONFIGURED\x10\t\x12\x1b\n\x17ST_CONNECTION_NOT_VALID\x10\n\x12\x13\n\x0fST_NVLINK_ERROR\x10\x0b\x32\x37\n\x10TelemetryService\x12#\n\x05Hello\x12\x0c.ClientHello\x1a\x0c.ServerHellob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nmx_telemetry_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _PROTOMSGMAJORVERSION._serialized_start = 528
    _PROTOMSGMAJORVERSION._serialized_end = 617
    _PROTOMSGMINORVERSION._serialized_start = 619
    _PROTOMSGMINORVERSION._serialized_end = 708
    _ST_RETURNCODE._serialized_start = 711
    _ST_RETURNCODE._serialized_end = 972
    _KEYVALPAIR._serialized_start = 23
    _KEYVALPAIR._serialized_end = 63
    _SERVERHEADER._serialized_start = 65
    _SERVERHEADER._serialized_end = 171
    _CLIENTHELLO._serialized_start = 173
    _CLIENTHELLO._serialized_end = 297
    _SERVERHELLO._serialized_start = 300
    _SERVERHELLO._serialized_end = 526
    _TELEMETRYSERVICE._serialized_start = 974
    _TELEMETRYSERVICE._serialized_end = 1029
# @@protoc_insertion_point(module_scope)
