# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ngts.tests_nvos.general.security.nmx_cert.grpc.nmx_t.proto.nmx_telemetry_pb2 as nmx__telemetry__pb2


class TelemetryServiceStub(object):
    """The RPCs are independent by design. As discussed with NMX-M, there is no requirement to track the clients state.
    Therefore no restrictions in the RPC call order.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
            '/TelemetryService/Hello',
            request_serializer=nmx__telemetry__pb2.ClientHello.SerializeToString,
            response_deserializer=nmx__telemetry__pb2.ServerHello.FromString,
        )


class TelemetryServiceServicer(object):
    """The RPCs are independent by design. As discussed with NMX-M, there is no requirement to track the clients state.
    Therefore no restrictions in the RPC call order.
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Hello': grpc.unary_unary_rpc_method_handler(
            servicer.Hello,
            request_deserializer=nmx__telemetry__pb2.ClientHello.FromString,
            response_serializer=nmx__telemetry__pb2.ServerHello.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class TelemetryService(object):
    """The RPCs are independent by design. As discussed with NMX-M, there is no requirement to track the clients state.
    Therefore no restrictions in the RPC call order.
    """

    @staticmethod
    def Hello(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TelemetryService/Hello',
                                             nmx__telemetry__pb2.ClientHello.SerializeToString,
                                             nmx__telemetry__pb2.ServerHello.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
