# name         lanes              alias     index
Ethernet0      0                  etp1a     1
Ethernet1      1                  etp1b     1
Ethernet2      2                  etp1c     1
Ethernet3      3                  etp1d     1
Ethernet16     16                 etp3a     3
Ethernet17     17                 etp3b     3
Ethernet18     18                 etp3c     3
Ethernet19     19                 etp3d     3
Ethernet32     32                 etp5a     5
Ethernet33     33                 etp5b     5
Ethernet34     34                 etp5c     5
Ethernet35     35                 etp5d     5
Ethernet48     48                 etp7a     7
Ethernet49     49                 etp7b     7
Ethernet50     50                 etp7c     7
Ethernet51     51                 etp7d     7
Ethernet64     64                 etp9a     9
Ethernet65     65                 etp9b     9
Ethernet66     66                 etp9c     9
Ethernet67     67                 etp9d     9
Ethernet80     80                 etp11a    11
Ethernet81     81                 etp11b    11
Ethernet82     82                 etp11c    11
Ethernet83     83                 etp11d    11
Ethernet96     96,97,98,99        etp13a    13
Ethernet100    100,101,102,103    etp13b    13
Ethernet112    112                etp15a    15
Ethernet113    113                etp15b    15
Ethernet114    114                etp15c    15
Ethernet115    115                etp15d    15
Ethernet128    128,129,130,131    etp17a    17
Ethernet132    132,133,134,135    etp17b    17
Ethernet144    144                etp19a    19
Ethernet145    145                etp19b    19
Ethernet146    146                etp19c    19
Ethernet147    147                etp19d    19
Ethernet160    160                etp21a    21
Ethernet161    161                etp21b    21
Ethernet162    162                etp21c    21
Ethernet163    163                etp21d    21
Ethernet176    176                etp23a    23
Ethernet177    177                etp23b    23
Ethernet178    178                etp23c    23
Ethernet179    179                etp23d    23
Ethernet192    192                etp25a    25
Ethernet193    193                etp25b    25
Ethernet194    194                etp25c    25
Ethernet195    195                etp25d    25
Ethernet208    208                etp27a    27
Ethernet209    209                etp27b    27
Ethernet210    210                etp27c    27
Ethernet211    211                etp27d    27
Ethernet224    224                etp29a    29
Ethernet225    225                etp29b    29
Ethernet226    226                etp29c    29
Ethernet227    227                etp29d    29
Ethernet240    240                etp31a    31
Ethernet241    241                etp31b    31
Ethernet242    242                etp31c    31
Ethernet243    243                etp31d    31
Ethernet252    248,249,250,251,252,253,254,255    etp32     32