- header:
    model: QM3400
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: 25.02.0076
- set:
    system:
      message:
        post-login: yoavpost
        pre-login: yoavpre123
    interface:
      swA1p1,swA2p1:
        link:
          connection-mode: ndr
        type: ib
