##
## Copyright (c) 2020-2021 NVIDIA CORPORATION & AFFILIATES.
## Apache-2.0
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
# name           lanes                alias            index
Ethernet0         0                 etp1a              1
Ethernet1         1                 etp1b              1
Ethernet2         2                 etp1c              1
Ethernet3         3                 etp1d              1
Ethernet8         16                etp3a              3
Ethernet9         17                etp3b              3
Ethernet10        18                etp3c              3
Ethernet11        19                etp3d              3
Ethernet16        32                etp5a              5
Ethernet17        33                etp5b              5
Ethernet18        34                etp5c              5
Ethernet19        35                etp5d              5
Ethernet24        48                etp7a              7
Ethernet25        49                etp7b              7
Ethernet26        50                etp7c              7
Ethernet27        51                etp7d              7
Ethernet32        64                etp9a              9
Ethernet33        65                etp9b              9
Ethernet34        66                etp9c              9
Ethernet35        67                etp9d              9
Ethernet40        80                etp11a              11
Ethernet41        81                etp11b              11
Ethernet42        82                etp11c              11
Ethernet43        83                etp11d              11
Ethernet48        96                etp13a              13
Ethernet49        97                etp13b              13
Ethernet50        98                etp13c              13
Ethernet51        99                etp13d              13
Ethernet56        112               etp15a              15
Ethernet57        113               etp15b              15
Ethernet58        114               etp15c              15
Ethernet59        115               etp15d              15
Ethernet64        128               etp17a              17
Ethernet65        129               etp17b              17
Ethernet66        130               etp17c              17
Ethernet67        131               etp17d              17
Ethernet72        144               etp19a              19
Ethernet73        145               etp19b              19
Ethernet74        146               etp19c              19
Ethernet75        147               etp19d              19
Ethernet80        160               etp21a              21
Ethernet81        161               etp21b              21
Ethernet82        162               etp21c              21
Ethernet83        163               etp21d              21
Ethernet88        176               etp23a              23
Ethernet89        177               etp23b              23
Ethernet90        178               etp23c              23
Ethernet91        179               etp23d              23
Ethernet96        192               etp25a              25
Ethernet97        193               etp25b              25
Ethernet98        194               etp25c              25
Ethernet99        195               etp25d              25
Ethernet104        208               etp27a              27
Ethernet105        209               etp27b              27
Ethernet106        210               etp27c              27
Ethernet107        211               etp27d              27
Ethernet112        224               etp29a              29
Ethernet113        225               etp29b              29
Ethernet114        226               etp29c              29
Ethernet115        227               etp29d              29
Ethernet120        240               etp31a              31
Ethernet121        241               etp31b              31
Ethernet122        242               etp31c              31
Ethernet123        243               etp31d              31
Ethernet128        256               etp33a              33
Ethernet129        257               etp33b              33
Ethernet130        258               etp33c              33
Ethernet131        259               etp33d              33
Ethernet136        272               etp35a              35
Ethernet137        273               etp35b              35
Ethernet138        274               etp35c              35
Ethernet139        275               etp35d              35
Ethernet144        288               etp37a              37
Ethernet145        289               etp37b              37
Ethernet146        290               etp37c              37
Ethernet147        291               etp37d              37
Ethernet152        304               etp39a              39
Ethernet153        305               etp39b              39
Ethernet154        306               etp39c              39
Ethernet155        307               etp39d              39
Ethernet160        320               etp41a              41
Ethernet161        321               etp41b              41
Ethernet162        322               etp41c              41
Ethernet163        323               etp41d              41
Ethernet168        336               etp43a              43
Ethernet169        337               etp43b              43
Ethernet170        338               etp43c              43
Ethernet171        339               etp43d              43
Ethernet176        352               etp45a              45
Ethernet177        353               etp45b              45
Ethernet178        354               etp45c              45
Ethernet179        355               etp45d              45
Ethernet184        368               etp47a              47
Ethernet185        369               etp47b              47
Ethernet186        370               etp47c              47
Ethernet187        371               etp47d              47
Ethernet192        384               etp49a              49
Ethernet193        385               etp49b              49
Ethernet194        386               etp49c              49
Ethernet195        387               etp49d              49
Ethernet200        400               etp51a              51
Ethernet201        401               etp51b              51
Ethernet202        402               etp51c              51
Ethernet203        403               etp51d              51
Ethernet208        416               etp53a              53
Ethernet209        417               etp53b              53
Ethernet210        418               etp53c              53
Ethernet211        419               etp53d              53
Ethernet216        432               etp55a              55
Ethernet217        433               etp55b              55
Ethernet218        434               etp55c              55
Ethernet219        435               etp55d              55
Ethernet224        448               etp57a              57
Ethernet225        449               etp57b              57
Ethernet226        450               etp57c              57
Ethernet227        451               etp57d              57
Ethernet232        464               etp59a              59
Ethernet233        465               etp59b              59
Ethernet234        466               etp59c              59
Ethernet235        467               etp59d              59
Ethernet240        480               etp61a              61
Ethernet241        481               etp61b              61
Ethernet242        482               etp61c              61
Ethernet243        483               etp61d              61
Ethernet248        496,497,498,499   etp63               63
Ethernet252        504,505,506,507   etp64               64